ShopTARgv24/ShopTARgv24/Models/RealEstates/RealEstateCreateUpdateViewModel.cs
namespace ShopTARgv24.Models.RealEstates
{
    public class RealEstateCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public double? Area { get; set; }
        public string? Location { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public List<IFormFile> Files { get; set; }
        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();

        public DateTime? CreateAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARgv24/ShopTARgv24/Models/RealEstates/RealEstateDeleteViewModel.cs
namespace ShopTARgv24.Models.RealEstates
{
    public class RealEstateDeleteViewModel
    {
        public Guid? Id { get; set; }
        public double? Area { get; set; }
        public string? Location { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();

        public DateTime? CreateAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARgv24/ShopTARgv24/Models/RealEstates/RealEstateDetailsViewModel.cs
namespace ShopTARgv24.Models.RealEstates
{
    public class RealEstateDetailsViewModel
    {
        public Guid? Id { get; set; }
        public double? Area { get; set; }
        public string? Location { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();

        public DateTime? CreateAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARgv24/ShopTARgv24/Models/RealEstates/RealEstateImageViewModel.cs
namespace ShopTARgv24.Models.RealEstates
{
    public class RealEstateImageViewModel
    {
        public Guid Id { get; set; }
        public string? ImageTitle { get; set; }
        public byte[]? ImageData { get; set; }
        public string? Image { get; set; }
        public Guid? RealEstateId { get; set; }
    }
}

ShopTARgv24/ShopTARgv24/Models/RealEstates/RealEstatesIndexViewModel.cs
namespace ShopTARgv24.Models.RealEstates
{
    public class RealEstatesIndexViewModel
    {
        public Guid? Id { get; set; }
        public double? Area { get; set; }
        public string? Location { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARgv24/ShopTARgv24/Models/Spaceships/ImageViewModel.cs
namespace ShopTARgv24.Models.Spaceships
{
    public class ImageViewModel
    {
        public Guid ImageId { get; set; }
        public string? FilePath { get; set; }
        public Guid? SpaceshipId { get; set; }
    }
}

ShopTARgv24/ShopTARgv24/Controllers/RealEstateController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopTARgv24.ApplicationServices.Services;
using ShopTARgv24.Core.Dto;
using ShopTARgv24.Core.ServiceInterface;
using ShopTARgv24.Data;
using ShopTARgv24.Models.RealEstates;
using ShopTARgv24.Models.Spaceships;

namespace ShopTARgv24.Controllers
{
    public class RealEstateController : Controller
    {
        private readonly ShopTARgv24Context _context;
        private readonly IRealEstateServices _realEstateServices;

        public RealEstateController
            (
                ShopTARgv24Context context,
                IRealEstateServices realEstateServices
            )
        {
            _context = context;
            _realEstateServices = realEstateServices;
        }

        public IActionResult Index()
        {
            var result = _context.RealEstates
                .Select(x => new RealEstatesIndexViewModel
                {
                    Id = x.Id,
                    Area = x.Area,
                    BuildingType = x.BuildingType,
                    RoomNumber = x.RoomNumber,
                });

            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            RealEstateCreateUpdateViewModel result = new();

            return View("CreateUpdate", result);
        }

        [HttpPost]
        public async Task<IActionResult> Create(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Area = vm.Area,
                BuildingType = vm.BuildingType,
                RoomNumber = vm.RoomNumber,
                Location = vm.Location,
                CreateAt = vm.CreateAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.Id,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        RealEstateId = x.RealEstateId,
                    }).ToArray()
            };

            var result = await _realEstateServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var realEstate = await _realEstateServices.DetailAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            RealEstateImageViewModel[] photos = await FilesFromDatabase(id);

            var vm = new RealEstateCreateUpdateViewModel();

            vm.Id = realEstate.Id;
            vm.Area = realEstate.Area;
            vm.BuildingType = realEstate.BuildingType;
            vm.RoomNumber = realEstate.RoomNumber;
            vm.Location = realEstate.Location;
            vm.CreateAt = realEstate.CreateAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.Image.AddRange(photos);

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Area = vm.Area,
                BuildingType = vm.BuildingType,
                RoomNumber = vm.RoomNumber,
                Location = vm.Location,
                CreateAt = vm.CreateAt,
                ModifiedAt = vm.ModifiedAt,
            };

            var result = await _realEstateServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var realEstate = await _realEstateServices.DetailAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            RealEstateImageViewModel[] photos = await FilesFromDatabase(id);

            var vm = new RealEstateDeleteViewModel();

            vm.Id = realEstate.Id;
            vm.Area = realEstate.Area;
            vm.BuildingType = realEstate.BuildingType;
            vm.RoomNumber = realEstate.RoomNumber;
            vm.Location = realEstate.Location;
            vm.CreateAt = realEstate.CreateAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.Image.AddRange(photos);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var realEstate = await _realEstateServices.Delete(id);

            if (realEstate == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            //kasutada service classi meetodit, et info k'tte saada
            var realEstate = await _realEstateServices.DetailAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            RealEstateImageViewModel[] photos = await FilesFromDatabase(id);

            var vm = new RealEstateDetailsViewModel();

            vm.Id = realEstate.Id;
            vm.Area = realEstate.Area;
            vm.BuildingType = realEstate.BuildingType;
            vm.RoomNumber = realEstate.RoomNumber;
            vm.Location = realEstate.Location;
            vm.CreateAt = realEstate.CreateAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.Image.AddRange(photos);

            return View(vm);
        }

        private async Task<RealEstateImageViewModel[]> FilesFromDatabase(Guid id)
        {
            return await _context.FileToDatabase
                .Where(x => x.RealEstateId == id)
                .Select(y => new RealEstateImageViewModel
                {
                    RealEstateId = y.Id,
                    Id = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64, {0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();
        }
    }
}

ShopTARgv24/ShopTARgv24/Views/RealEstate/CreateUpdate.cshtml
@model ShopTARgv24.Models.RealEstates.RealEstateCreateUpdateViewModel


@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}



<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden"/>
        <input asp-for="CreateAt" type="hidden" />
        <input asp-for="ModifiedAt" type="hidden"/>

        <div class="form-group row">
            <label asp-for="Area" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Area" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Location" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Location" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="RoomNumber" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="BuildingType" class="form-control" />
            </div>
        </div>




        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="realestate" type="submit" class="btn btn-primary" value="Update" />
            
        }
        else
        {
            <input asp-action="create" asp-controller="realestate" type="submit" class="btn btn-primary" value="Create" />
        }
        <a asp-action="Index" asp-controller="realestate" class="btn btn-success">Back</a>

    </form>
</div>

ShopTARgv24/ShopTARgv24/Views/RealEstate/Delete.cshtml
@model ShopTARgv24.Models.RealEstates.RealEstateDeleteViewModel

<h1>Delete</h1>

<div>
    <h4>Spaceship</h4>
    <hr />
    <dl class="row">
        <div class="form-group row"> 
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.Id)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Area" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.Area)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Location" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.Location)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.RoomNumber)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.BuildingType)
        </div>
    </dl>


    <dl class="row">
        <div class="form-group row">
            <label asp-for="CreateAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.CreateAt)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.ModifiedAt)
        </div>
    </dl>

    <form asp-action="DeleteConfirmation">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="index" asp-controller="realestate" class="btn btn-primary">Back</a>
    </form>

</div>

ShopTARgv24/ShopTARgv24/Views/RealEstate/Details.cshtml
@model ShopTARgv24.Models.RealEstates.RealEstateDetailsViewModel

<h1>Details</h1>

<div>
    <h4>RealEstate</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.Id)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Area" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.Area)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Location" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.Location)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.RoomNumber)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.BuildingType)
        </div>
    </dl>


    <dl class="row">
        <div class="form-group row">
            <label asp-for="CreateAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.CreateAt)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(Model => Model.ModifiedAt)
        </div>




        <form>

    <a asp-action="index" asp-controller="RealEstate" class="btn btn-primary">Back</a>
        </form>
</div>

ShopTARgv24/ShopTARgv24/Views/RealEstate/Index.cshtml
@model IEnumerable<ShopTARgv24.Models.RealEstates.RealEstatesIndexViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="realestate" type="submit" class="btn btn-primary">Create</a>
</div>

<div class="h1">
    RealEstate
</div>
<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Area</th>
                <th scope="col">Location</th>
                <th scope="col">RoomNumber</th>
                <th scope="col">BuildingType</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var realestate in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@realestate.Area</td>
                    <td>@realestate.Location</td>
                    <td>@realestate.RoomNumber</td>
                    <td>@realestate.BuildingType</td>
                    <td>
                        <a asp-action="details" asp-controller="realestate" asp-route-id="@realestate.Id" class="btn btn-primary">Details</a>
                        <a asp-action="update" asp-controller="realestate" asp-route-id="@realestate.Id" class="btn btn-primary">Update</a>
                        <a asp-action="delete" asp-controller="realestate" asp-route-id="@realestate.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>

                rowNumber += 1;
            }
        </tbody>
    </table>
</form>

ShopTARgv24/ShopTARgv24/Views/RealEstate/_Images.cshtml
@model ShopTARgv24.Models.RealEstates.RealEstateImageViewModel

<div class="form-group row col-sm-4 offset-2">
    <div>@Model.ImageTitle</div>
    <img class="card-img-top" src="@Model.Image" asp-append-version="true" />
</div>